apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skapp-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-username/your-repo.git'
    targetRevision: HEAD
    path: helm/skapp         # Folder containing your Helm chart
    helm:
      releaseName: sasiclahan
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
