backend:
  replicaCount: 2
  image:
    repository: 545009835959.dkr.ecr.eu-central-1.amazonaws.com/clahanbackend
    tag: latest
  service:
    type: ClusterIP
    port: 5000
  containerPort: 5000
  env:
    DB_HOST: "clahandb.cjawyscksd9j.eu-central-1.rds.amazonaws.com"
    DB_USER: "postgres"
    DB_PASSWORD: "postgres"
    DB_NAME: "postgres"

frontend:
  replicaCount: 1
  image:
    repository: 545009835959.dkr.ecr.eu-central-1.amazonaws.com/clahanfrontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  containerPort: 80
